config/routes.rb
Rails.application.routes.draw do
  
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :settings, only: [:edit, :update]
  
  resources :users, only: [:index, :show] do
    resource :follows, only: [:create, :destroy]
    get :favorites, on: :member
    get :accepts, on: :member
    get :follows, on: :member
    get :followers, on: :member
  end
  
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    get :timeline, on: :collection
  end

  resources :reports do
    resource :accepts, only: [:create, :destroy]
    get :bibliographies, on: :member
  end
  
  resources :bibliographies do
    get :reports, on: :member
  end
  
  root to: 'registrations#new'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :favorites, dependent: :destroy
  
  validates :user, presence: true
  validates :content, presence: true, length: { in: 1..1024}
  
  def favorited_by? user
    favorites.where(user_id: user.id).exists?
  end
  
  default_scope -> { order(created_at: :desc) }
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :require_login, except: [:index]
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end
  
  def timeline
    @tweets = Tweet.eager_load(user: :inverse_follows).where(follows: { follower_id: current_user.id })
  	@tweet = Tweet.new
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        @tweets = Tweet.all
        format.html { render :index }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :content
    = f.text_field :content
  .actions
    = f.submit 'Save'

app/views/tweets/_panel.html.haml
- if logged_in?
  .panel.panel-default
    .panel-body
      = link_to user_path(current_user), class: "user" do
        %span.user-name
          = render_user_screen_name current_user
        %span.user-id
          @#{current_user.name}
      .user-activity
        .row
          .col-xs-4.tweet-num
            .text
              つぶやき
            .num
              = link_to current_user.tweets.count, user_path(current_user)
          .col-xs-4.follow-num
            .text
              フォロー
            .num
              = link_to current_user.inverse_followers.count, follows_user_path(current_user)
          .col-xs-4.follower-num
            .text
              フォロワー
            .num
              = link_to current_user.followers.count, followers_user_path(current_user)
      - @tweet.errors.full_messages.each do |message|
        .alert.alert-danger= message
      = form_for @tweet do |f|
        .form-group
          = f.text_area :content, class: "form-control"
        = f.submit "つぶやく", class: "btn btn-success"

app/views/tweets/edit.html.haml
%h1 Editing tweet

= render 'form'

= link_to 'Show', @tweet
\|
= link_to 'Back', tweets_path

app/views/tweets/index.html.haml
#tweets-content
  .container
    .row
      .col-xs-4.left-content
        - if logged_in?
          .panel.panel-default
            .panel-body
              = link_to user_path(current_user), class: "user" do
                %span.user-name
                  = render_user_screen_name current_user
                %span.user-id
                  @#{current_user.name}
              .user-activity
                .row
                  .col-xs-4.tweet-num
                    .text
                      つぶやき
                    .num
                      = link_to current_user.tweets.count, user_path(current_user)
                  .col-xs-4.follow-num
                    .text
                      フォロー
                    .num
                      0
                  .col-xs-4.follower-num
                    .text
                      フォロワー
                    .num
                      0
              - @tweet.errors.full_messages.each do |message|
                .alert.alert-danger= message
              = form_for @tweet do |f|
                .form-group
                  = f.text_area :content, class: "form-control"
                = f.submit "つぶやく", class: "btn btn-success"
      .col-xs-8.right-content
        - if notice
          .alert.alert-info= notice
        .list-group
          = div_for @tweets, class: "list-group-item" do |t|
            %h4.user
              %span.user-name
                = link_to render_user_screen_name(t.user), user_path(t.user)
              %span.user-id
                @#{t.user.name}
              %span.time.pull-right
                = distance_of_time_in_words_to_now(t.created_at)
              .clear
            .tweet-content
              %p
                = t.content
              .content-footer
                - if t.favorited_by? current_user
                  = link_to "お気に入りに解除", tweet_favorites_path(t), method: :delete
                - else
                  = link_to "お気に入りに登録", tweet_favorites_path(t), method: :post

app/views/tweets/new.html.haml
%h1 New tweet

= render 'form'

= link_to 'Back', tweets_path

app/views/tweets/show.html.haml
%p#notice= notice

%p
  %b User:
  = @tweet.user_id
%p
  %b Content:
  = @tweet.content

= link_to 'Edit', edit_tweet_path(@tweet)
\|
= link_to 'Back', tweets_path

app/views/tweets/timeline.html.haml
#tweets-content
  .container
    .row
      .col-xs-4.left-content
        = render partial: "panel"
      .col-xs-8.right-content
        - if notice
          .alert.alert-info= notice
        .list-group
          .list-group-item
            .btn-group
              = link_to "すべてのつぶやき", tweets_path, class: "active btn btn-primary"
              = link_to "フォローしている人のつぶやき", timeline_tweets_path, class: "btn btn-default"
          = render partial: "users/tweet", collection: @tweets