config/routes.rb
Rails.application.routes.draw do
  
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :settings, only: [:edit, :update]
  
  resources :users, only: [:index, :show] do
    resource :follows, only: [:create, :destroy]
    get :favorites, on: :member
    get :accepts, on: :member
    get :follows, on: :member
    get :followers, on: :member
  end
  
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    get :timeline, on: :collection
  end

  resources :reports do
    resource :accepts, only: [:create, :destroy]
    get :bibliographies, on: :member
  end
  
  resources :bibliographies do
    get :reports, on: :member
  end
  
  root to: 'registrations#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :accepts, dependent: :destroy
  
  has_many :follows, foreign_key: :follower_id
  has_many :inverse_followers, through: :follows
  has_many :inverse_follows, foreign_key: :inverse_follower_id, class_name: Follow
  has_many :followers, through: :inverse_follows
  
  has_many :reports, dependent: :destroy
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-z][a-z0-9]+\z/ }, length: { in: 4..24 }
  validates :screen_name, length: { maximum: 140 }
  validates :bio, length: { maximum: 200  }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, confirmation: true, length: { in: 6..24 }, if: :password
  validates :password_confirmation, presence: true, if: :password
  
  def followed_by? user
    inverse_follows.where(follower_id: user.id).exists?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end
  
  def favorites
    @user = User.find(params[:id])
  end
  
  def accepts
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def follows
    @user = User.find(params[:id])
  end
  
  def followers
    @user = User.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def render_user_screen_name user
    if user.screen_name.blank?
      user.name
    else
      user.screen_name
    end
  end
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/users/_header.html.haml
.user-info
  - if notice
    .alert.alert-info= notice
  %span.user-name
    = render_user_screen_name(@user)
  %span.user-id
    @#{@user.name}
  .bio
    = @user.bio

%ul.nav.nav-tabs.nav-justified
  %li{class: action_name == "show" ? "active" : nil}
    = link_to user_path(@user) do
      .text
        つぶやき
      .num
        #{@user.tweets.count}
  %li{ class: action_name == "follows" ? "active" : nil }
    = link_to follows_user_path(@user) do
      .text
        フォロー
      .num
        #{@user.inverse_followers.count}
  %li{ class: action_name == "follwers" ? "active" : nil }
    = link_to followers_user_path(@user) do
      .text
        フォロワー
      .num
        #{@user.followers.count}
  %li{class: action_name == "favorites" ? "active" : nil}
    = link_to favorites_user_path(@user) do
      .text
        お気に入り
      .num
        #{@user.favorites.count}
  %li{class: action_name == "accepts" ? "active" : nil}
    = link_to accepts_user_path(@user) do
      .text
        課題
      .num
        #{@user.accepts.count}

app/views/users/_report.html.haml
= div_for report, class: "list-group-item" do |t|
  %h4.user
    %span.user-name
      = link_to t.name, report_path(t)
    %span.user-id
      締切日 #{t.timelimit}
    %span.time.pull-right
      = distance_of_time_in_words_to_now(t.created_at)
    .clear
  .tweet-content
    %p
      = t.description
    .content-footer
      - if t.accepted_by? current_user
        = link_to "課題終了", report_accepts_path(t), method: :delete
      - else
        = link_to "この課題に着手", report_accepts_path(t), method: :post

app/views/users/_tweet.html.haml
= div_for tweet, class: "list-group-item" do |t|
  %h4.user
    %span.user-name
      = link_to t.user.name, user_path(t.user)
    %span.user-id
      @#{t.user.name}
    %span.time.pull-right
      = distance_of_time_in_words_to_now(t.created_at)
    .clear
  .tweet-content
    %p
      = t.content
    .content-footer
      - if t.favorited_by? current_user
        = link_to "お気に入りに解除", tweet_favorites_path(t), method: :delete
      - else
        = link_to "お気に入りに登録", tweet_favorites_path(t), method: :post
      - if t.user.followed_by? current_user
        = link_to "フォロー解除", user_follows_path(t.user), method: :delete
      - else
        = link_to "フォロー", user_follows_path(t.user), method: :post

app/views/users/_user.html.haml
= div_for user, class: "list-group-item" do |u|
  %h4.user
    %span.user-name
      = link_to u.name, user_path(u)
    %span.user-id
      @#{u.name}
  .bio
    = u.bio
  .follow-unfollow
    - if u.followed_by? current_user
      = link_to "フォロー解除", user_follows_path(u), method: :delete
    - else
      = link_to "フォロー", user_follows_path(u), method: :post

app/views/users/accepts.html.haml
.col-xs-8#users-content
  = render partial: "users/header"
  .list-group
    - if @user.accepts.empty?
      .list-group-item
        着手中の課題はありません
    = render partial: "users/report", collection: @user.accepts.map{|f| f.report}

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/favorites.html.haml
.col-xs-8#users-content
  = render partial: "users/header"
  .list-group
    - if @user.favorites.empty?
      .list-group-item
        まだお気に入りに登録されたツイートはありません
    = render partial: "users/tweet", collection: @user.favorites.map{|f| f.tweet}

app/views/users/followers.html.haml
.col-xs-8#users-content
  = render partial: "users/header"
  .list-group
    = render @user.followers

app/views/users/follows.html.haml
.col-xs-8#users-content
  = render partial: "users/header"
  .list-group
    = render @user.inverse_followers

app/views/users/index.html.haml
.col-xs-8#users-content
  .list-group
    .list-group-item.user-list
      %h2 ユーザー一覧
    = render partial: "users/user", collection: @users

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
.col-xs-8#users-content
  = render partial: "users/header"
  .list-group
    - if @user.tweets.empty?
      .list-group-item
        Let's Tweet!
    = render partial: "users/tweet", collection: @user.tweets