config/routes.rb
Rails.application.routes.draw do
  
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :settings, only: [:edit, :update]
  
  resources :users, only: [:index, :show] do
    resource :follows, only: [:create, :destroy]
    get :favorites, on: :member
    get :accepts, on: :member
    get :follows, on: :member
    get :followers, on: :member
  end
  
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    get :timeline, on: :collection
  end

  resources :reports do
    resource :accepts, only: [:create, :destroy]
    get :bibliographies, on: :member
  end
  
  resources :bibliographies do
    get :reports, on: :member
  end
  
  root to: 'registrations#new'

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  has_many :accepts, dependent: :destroy
  has_many :bibliographies, dependent: :destroy
  
  validates :user, presence: true, length: { maximum: 50 }
  validates :timelimit, presence: true
  validates :description, presence: true
  
  default_scope -> { order(created_at: :desc) }
  
  def accepted_by? user
    accepts.where(user_id: user.id).exists?
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :require_login, except: [:index]
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @report = Report.new
    @reports = Report.all
    @bgcolor = '#ff0000'
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    @report.user = current_user

    respond_to do |format|
      if @report.save
        format.html { redirect_to reports_url, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :timelimit, :description)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= form_for @report do |f|
  - if @report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      %ul
        - @report.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :timelimit
    = f.date_select :timelimit
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/reports/edit.html.haml
#new-reports-edit
  .col-xs-6.new-reports-content
    = form_for @report do |f|
      %h2
        課題の編集
      .form-body
        .form-group
          = f.label :name, "タイトル", class: "control-label"
          = f.text_field :name, class: "form-control"
        .form-group
          = f.label :date, "締切日", class: "control-label"
          %br
          = f.date_select :timelimit, class: "form-control"
        .form-group
          = f.label :description, "説明", class: "control-label"
          = f.text_area :description, class: "form-control"
        = f.submit "送信する", class: "btn btn-success"

app/views/reports/index.html.haml
.col-xs-8#reports-content
  - if notice
    .alert.alert-info= notice
  .list-group
    .list-group-item.report-list
      %h2 課題一覧
    = button_to 'New', new_report_path(@report), method: :get, class: "btn-block btn-success"
    = div_for @reports, class: "list-group-item" do |r|
      %h4.report
        %span.report-name
          #{r.id}.
          %b
            = link_to r.name, report_path(r)
            - if (r.timelimit - Date.today).to_i < 0
              %i.fa.fa-ban
            - elsif (r.timelimit - Date.today).to_i < 2
              %i.fa.fa-exclamation-triangle
            - elsif (r.timelimit - Date.today).to_i < 7
              %i.fa.fa-pencil-square-o
        %span.report-timelimit
          締切日 #{r.timelimit}
      .discription
        = r.description
      .content-footer
        - if r.accepted_by? current_user
          = link_to "課題終了", report_accepts_path(r), method: :delete
        - else
          = link_to "この課題に着手", report_accepts_path(r), method: :post

app/views/reports/new.html.haml
#new-reports-edit
  .col-xs-6.new-reports-content
    = form_for @report do |f|
      %h2
        新しい課題
      .form-body
        .form-group
          = f.label :name, "タイトル", class: "control-label"
          = f.text_field :name, class: "form-control"
        .form-group
          = f.label :date, "締切日", class: "control-label"
          %br
          = f.date_select :timelimit, class: "form-control"
        .form-group
          = f.label :description, "説明", class: "control-label"
          = f.text_area :description, class: "form-control"
        = f.submit "送信する", class: "btn btn-success"

app/views/reports/show.html.haml
#reports-show
  .col-xs-6.reports-content
    .box
      %h2
        = @report.name
      .box-body
        .control-label
          = @report.timelimit
        %h4
          = @report.description
        = button_to 'Edit', edit_report_path(@report), method: :get, class: "btn-block btn-success"
        = button_to 'Back', reports_path, method: :get, class: "btn-block btn-success"
  .col-xs-6.reports-content
    .box
      %h2
        参考文献
      .box-body
        = button_to 'New', new_bibliography_path(@report), method: :get, class: "btn-block btn-success"
        - if @report.bibliographies.empty?
          まだ参考文献がありません
        = div_for @report.bibliographies, class: "list-group-item" do |t|
          %h4.user
            %span.user-name
              = link_to t.name, t.url, :target=>["_blank"] 