config/routes.rb
Rails.application.routes.draw do
  
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :settings, only: [:edit, :update]
  
  resources :users, only: [:index, :show] do
    resource :follows, only: [:create, :destroy]
    get :favorites, on: :member
    get :accepts, on: :member
    get :follows, on: :member
    get :followers, on: :member
  end
  
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    get :timeline, on: :collection
  end

  resources :reports do
    resource :accepts, only: [:create, :destroy]
    get :bibliographies, on: :member
  end
  
  resources :bibliographies do
    get :reports, on: :member
  end
  
  root to: 'registrations#new'

end

app/views/layouts/_header.html.haml
.navbar.navbar-default
  .container
    .navbar-header
      = link_to '#推特', root_url, class: "navbar-brand"
    - if logged_in?
      %ul.nav.navbar-nav
        %li= link_to "全ツイート一覧", tweets_path
        %li= link_to "課題一覧", reports_path
        %li= link_to "ユーザー一覧", users_path
      %ul.nav.navbar-nav.navbar-right
        %li= link_to current_user.name, current_user
        %li= link_to "設定", edit_settings_path
        %li= link_to "ログアウト", sessions_path, method: :delete
    - else
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "会員登録", new_registrations_path
        %li= link_to "ログイン", new_sessions_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="application">

<div>
  <%= render partial: "layouts/header" %>
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/registrations.html.haml
!!!
%html
%head
  %title klis05
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body#registrations
  = yield

app/views/layouts/sessions.html.haml
!!!
%html
%head
  %title DenDen047
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body#sessions
  = yield